; m5stack-water-reminder — hydration reminder firmware for M5StickC Plus
; Copyright (c) 2026 Ramy Ezzat
; SPDX-License-Identifier: MIT

[env:m5stickc-plus]
platform = espressif32
board = m5stick-c
framework = arduino
; upload_port = COM23
; monitor_port = COM23
monitor_speed = 115200
build_flags =
    -DCORE_DEBUG_LEVEL=0
lib_deps =
    m5stack/M5StickCPlus
